### ISSUE TITLE
Empty docs_readme file

### ISSUE THREAD

**Issue by staveesh** [noise-lab/netml#13]
I was looking for some information on how to concatenate IAT features for 2 kinds of flows if the number of columns do not match. The file https://github.com/chicago-cdac/netml/blob/master/docs/docs_readme.md is currently empty. Is there a different docs file that I should be referring to?

**Comment by feamster** [comment]
@staveesh Tried to update the README a little bit. But we should make a github page for this project. I'll work on that.

**Comment by feamster** [comment]
Was thinking to eventually make a project webpage. Happy to do that in the docs directory and then we can switch over the github pages whenever I manage to find time to do that.

**Comment by jesteria** [comment]
Yep, I couldn't tell you why this was created. It should go away unless there's something to put there now.
